### ISSUE TITLE
Wrong redirect in link in sidebar of this repository

### ISSUE THREAD

**Issue by BioGeek** [mclaeysb/FerrarGIS#1]
Hey,

Great project!

Just a small nitpick: the link in the sidebar of this repository, https://mclaeysb.github.io/ferrargis/, redirects to https://manuelclaeysbouuaert.be/ferrargis/ which gives a 404 error. The URL should redirect to https://manuelclaeysbouuaert.be/projects/ferrargis.html

![image](https://user-images.githubusercontent.com/59344/167083141-b79e9acf-366e-4b5c-9365-380795cda726.png)

**Comment by mclaeysb** [comment]
Hey, thanks for letting me know! :) I've changed it. Glad you enjoyed this project.
