### ISSUE TITLE
Labels on the river / Lack of rail bridges

### ISSUE THREAD

**Issue by stalkerGH** [mclaeysb/FerrarGIS#4]
I encountered a problem with labels on the river. Sometimes they cover the bridges. When I try to move them by hand, using "Move a label" QGIS tool, the label behaves strangely - it rotates upside down and I can't find a way to put it in previous, right position.

Another problem is lack of rail bridges - railway tracks are visible but the bridges not.

I attach the images to illustrate the problems described above.

![wro1](https://user-images.githubusercontent.com/25331715/232338675-c709bb9e-72c5-4d70-8bda-a527ed6299f4.jpg)

![wro2](https://user-images.githubusercontent.com/25331715/232338677-4b44906b-77a9-421d-8764-3497047ffd31.jpg)

![wro3](https://user-images.githubusercontent.com/25331715/232338678-e077ce12-cdd3-4c49-94d6-2950e9354f0c.jpg)

**Comment by mclaeysb** [comment]
Hi there.

Cool to see you applied this style to another city! You indeed spotted two features missing in the current style. Feel free improve the style yourself in QGIS, and submit a PR if you think you improved it!

All the best
Manuel
